.github/ISSUE_TEMPLATE/bug_report.md
.gitignore
LICENSE
README.md
build-binutils.py
build-llvm.py
clang-version.sh
utils.py

As requested, the previous shell scripts have been rewriting in Python. Please feel free to let me know if there is something that could be done better, this is my first foray in Python after all :)
This passes my Docker testing ([script here](https://github.com/nathanchance/scripts/blob/63f77456dd396cd113e7eae08f2f8693cd8f5f77/funcs/cbl#L845-L919)), which takes a Docker image, sets up an environment, and runs the scripts.

tc-build: Python rewrite

---

build-llvm.py

This will make builds more reproducible and easier to manage over time,
as we don't have to worry as much about the user's environment because
they just need to be able to build stage 1 then stage 2 will be
consistent across environments.
This does take longer so an option '--stage1-only' is introduced for
users who have less powerful systems and instances like bisecting where
we just want a compiler to test something really quick.
There is another option introduced, '--thin-lto', which enabled ThinLTO
because we are using ld.lld. This can save some cycles (~5% speed up in
my experience) when using the toolchain.
The cmake defines are now logically split up into a couple of different
functions for easy ingestion and decisions based on what stage we are
at.

build-llvm.py: Split into a two-stage build

---

build-llvm.py

We save a few build targets this way.

build-llvm.py: Disable LLVM_INCLUDE_UTILS for stage 1

---

build-binutils.py
build-llvm.py

Some people might want to have their build folder elsewhere (like a
tmpfs mount) so add a parameter like the install folder one.

tc-build: Add '-B' parameter to change build folder

---

utils.py

Also, eliminate all of the unnecessary 'pathlib.Path' calls.

utils.py: Use more descriptive variable names in download_binutils

---

build-llvm.py

Without this, LLVM_ENABLE_PLUGINS does not get enabled after
https://github.com/llvm/llvm-project/commit/b7804ef3a746cd6c2c95c81eb19a81fb9df34cc6, which breaks LTO:
aarch64-linux-gnu-ld.gold: fatal error: LLVM gold plugin has failed to
create LTO module: Unknown attribute kind (60) (Producer: 'LLVM9.0.0svn'
Reader: 'LLVM 8.0.0')
I am not sure if this should be reported upstream or not since it seems like this is expected behavior now.

build-llvm.py: Enable LLVM_BUILD_LLVM_DYLIB

---

build-llvm.py

We do not use these things, which will save some build targets on stage
2. This was inspired by https://crrev.com/c/1629950.
Number of stage 2 targets before this commit: 4031
Number of stage 2 targets after this commit: 3703

build-llvm.py: Disable some more compiler-rt options

---

build-llvm.py

```
Traceback (most recent call last):
File "./build-llvm.py", line 719, in <module>
main()
File "./build-llvm.py", line 715, in main
do_multistage_build(args, dirs, env_vars)
File "./build-llvm.py", line 683, in do_multistage_build
install_folder = dirs.build_folder.joinpath("stage%d" % stage)
UnboundLocalError: local variable 'stage' referenced before assignment
```

build-llvm.py: Fix UnboundLocalError in do_multistage_build

---

build-llvm.py

We gain pretty much nothing from ccache after the first stage because we
are using a fresh compiler, unlike stage one, which uses the host
compiler that does not change very often.
A simple test of this:
1. Apply https://gist.github.com/80bb34c45687ba2e5889af64fd5a5b89 to
build-llvm.py (zero out ccache and print stats between stages).
2. $ ccache -Cz
3. $ ./build-llvm.py
Stage one cache hit rate: 0.00%
Stage two cache hit rate: 0.00%
4. $ git -C llvm-project checkout HEAD~50
5. $ ./build-llvm.py --no-pull
Stage one cache hit rate: 44.51%
Stage two cache hit rate: 0.00%
The primary motivation for this change is avoiding unnecessarily filling
the user's cache; each compiler can add anywhere from 200-300MB worth of
files to the cache, which will most likely not get used. Another
possible …

build-llvm.py: Don't use ccache past stage one

---

kernel/build.sh

Some users may only target cross targets like ARM and AArch64, meaning
we cannot generate X86 code on an x86_64 host:
```
HOSTCC  scripts/basic/fixdep
GEN     Makefile
error: unable to create target: 'No available targets are compatible with triple "x86_64-unknown-linux-gnu"'
1 error generated.
make[3]: *** [scripts/Makefile.host:92: scripts/basic/fixdep] Error 1
```
Just remove the `HOST{CC,LD}` variables so that we don't cause a build
error, the host tools are a minor part of the build process so we don't
lose out on any PGO coverage this way.
Reported-by: @0ctobot

kernel/build.sh: Do not supply host variables

---

build-llvm.py

Some users want this to be able to distinguish their builds from clang
upstream, either because of cherry-picks/reverts or to easily see if
their own build was what compiled their kernel or if it was the
system's.
cc @0ctobot @Wight554

build-llvm.py: Add an option to set the vendor string

---

kernel/build.sh

Some little improvements in handling Linux source tarballs:
Save download band width by using *.tar.xz tarballs from <kernel.org>
(Linux v5.2: approx. 50MiB).
Simplify the decompression of tarballs as modern tar versions are
smart enough to detect the (de)compressor.
Further improvements (TBD):
Verify the sign file [2]  of the desired Linux source tarball.
Details see tc-build issue #26:
"Linux sources: Download XZ tarball, simplify decompressing and verify sign-file"
[1] https://github.com/ClangBuiltLinux/tc-build/issues/26
[2] https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.2.tar.sign

kernel/build.sh: Improve handling of Linux source tarballs

---

build-llvm.py

We don't need them and it significantly reduces the targets on a stage 1
PGO build:
Targets before: 3513
Targets after: 2661

build-llvm.py: Disable compiler-rt sanitizers for stage 1 bootstraps

---

kernel/build.sh
kernel/linux-5.2-allyesconfig.patch
utils.py

The first patch fixes a couple of shellcheck warnings.
The second patch allows the kernel build script to do allyesconfig builds, which can be helpful for benchmarking changes like PGO and adding assertions. The commit message explains more.
The third patch just formats `utils.py` with [YAPF](https://github.com/google/yapf).
Let me know if there are any concerns.

Three miscellaneous improvements

---

build-llvm.py

Make it explicitly clear what this flag does and how it is used.

build-llvm.py: Improve '--check-targets' help text

---

build-llvm.py

Tested with:
```
$ ./build-llvm.py --pgo --use-good-revision
$ PATH_OVERRIDE=${PWD}/install/bin ./kernel/build.sh --allyesconfig
```

build-llvm.py: Bump GOOD_REVISION

---

kernel/build.sh

This will make it easier to audit build failures because the exact make
command can be copy and pasted from the terminal.

kernel/build.sh: Show make command using set -x and only show warnings/errors

---

README.md

as binutils build request it, otherwise the build fails:
binutils/missing: 81: binutils/missing: flex: not found
WARNING: 'flex' is missing on your system.
You should only need it if you modified a '.l' file.
You may want to install the Fast Lexical Analyzer package:
<http://flex.sourceforge.net/>
make[2]: *** [Makefile:1108: syslex.c] Error 127
binutils/missing: 81: binutils/missing: bison: not found
WARNING: 'bison' is missing on your system.
You should only need it if you modified a '.y' file.
You may want to install the GNU Bison package:
<http://www.gnu.org/software/bison/>
make[2]: *** [Makefile:1111: sysinfo.c] Error 127

README.md: Add flex and bison to needed packages

---

utils.py

* Use xz because the download is smaller. This mirrors what we did for
the Linux kernel tarballs in commit 6aa9ba0 ("kernel/build.sh:
Improve handling of Linux source tarballs").
* Rename the verify_checksum function to make it clear that this is for
binutils.

utils: Update to binutils 2.33.1 and other small improvements

---

utils.py

Fix the comment after commit 7fc8133 ("utils: Update to binutils 2.33.1
and other small improvements") where we switched to xz compression.

tc-build: Update binutils to 2.34

---

build-llvm.py

We do not want assertions to be enabled on a stage 2 PGO build otherwise
profile generation will take ages.

build-llvm.py: Only enable assertions on the final build

---

build-llvm.py

There are times when one-time builds are desired (e.g. CI runs). Cloning the LLVM repo with history is wasteful in such cases because the history will never be used.
Add an option to perform a shallow clone rather than a full clone to speed up builds when history and updating are not required.

build-llvm.py: Add an option to perform shallow clones

---

README.md

Originally, I had listed the PGO packages as an aside because they were
just for building the kernels and I did not want to bloat people's
systems.
However, it has caused some headaches over time because they did not
realize that they needed more packages than the ones listed because the
PGO packages were listed in a paragraph below and it was not very clear.
Fix this by just moving the packages needed for --pgo to work into the
main list of packages; it won't hurt people.

README: Hoist PGO packages into list of packages to install

---

build-llvm.py

Also, add a variable so this becomes easier to bump. Eventually, I would like to do this similar to `driver.sh` in the CI repo where we just grab the latest version from the LLVM repo but that becomes hard in Python...

build-llvm.py: Look for clang-11 when building stage 1

---

build-llvm.py

More and more Android kernel developers are starting to enable Polly.
This was recently enabled in AOSP's LLVM builds:
https://android.googlesource.com/toolchain/llvm_android/+/6ba474f9d931f696860cec49b8c1dd62ac1e5a46
Do the same thing in our build. It only adds approximately 150 targets
to the final LLVM stage (comparing --build-stage1-only with and without
this patch, 3714 -> 3870).
While we're at it, alphabetize the projects.
cc @kdrag0n @0ctobot @lazerl0rd

build-llvm.py: Enable Polly by default

---

README.md

Users can manually manage LLVM's source if they need to, either due to
space/time requirements or doing things like bisection. Document this.
Closes: #75
cc @dileks

README: Document manual LLVM source management

---

README.md

In my Docker image tests, these couple of packages are necessary for
the build to complete properly.
xz is required after we switched to xz compression on Linux/binutils
tarballs.
texinfo has always been required but I must have left it off by accident
for Fedora since it is there for Debian/Ubuntu. It is a part of the
base-devel group on Arch Linux so no need to update it.

README: Update a few package lists

---

build-llvm.py

This reverts commit 04630c0621e607b260cbc12073feeaf2d13c96c1.
This was actually a bad idea. If assertions are not enabled when doing
PGO, they cannot be taken into account when optimizing hot paths.
Sample kernel build times with a PGO'd clang without assertions:
```
arm32 allyesconfig: 10m 48s
arm64 allyesconfig: 12m 21s
x86_64 allyesconfig: 14m 30s
```
Sample kernel build times with a PGO'd clang with assertions without
this patch:
```
arm32 allyesconfig: 14m 57s
arm64 allyesconfig: 17m 51s
x86_64 allyesconfig: 19m 24s
```
Sample kernel build times with a PGO'd clang with assertions with this
patch:
```
arm32 allyesconfig: 12m 24s
arm64 allyesconfig: 13m 55s
x86_64 allyesconfig: 15m 53s
```

Revert "build-llvm.py: Only enable assertions on the final build"

---

build-llvm.py
utils.py

Addresses #81 (cc @dileks) and some other things that I have thought of while investigating it.
I've written fairly detailed commit messages for each individual change. Some hammering on this would be appreciated as I think I have covered every corner case I can think of but I might have missed something.
@kdrag0n, please make sure this won't break your automated workflow.

tc-build: Improvements around '--shallow-clone'

---

.github/workflows/main.yml
clang-version.sh
kernel/build.sh

Uses [mvdan/sh](https://github.com/mvdan/sh) to enable formatting checks in CI, and correctly fails when the codestyle is [incorrect](https://github.com/msfjarvis/boot-utils/actions/runs/85612538), outputting a diff with fixes.
I chose the set of options that made the most sense to me, all available switches are listed [here](https://bin.msfjarvis.dev/~5ea167531de3ad00122e4ec0).

Reformat shell scripts with shfmt and validate in CI

---

build-llvm.py

Using full LTO requires a lot of memory. A machine with 32GB of
memory could not complete a build with `--lto=full` before getting
killed (see the link below).
To try and prevent people reporting issues with the script when it is
really their hardware (or lack of), swap the order of the LTO options
to make the thin option seem preferred and add a note about using full
LTO with less than 64GB of memory.
Link: https://www.packet.com/cloud/servers/c3-small/
References: #59
Closes: #85

build-llvm.py: Add a note about full LTO

---

build-llvm.py

I added the versioned binaries to handle the case where someone was
using apt.llvm.org binaries, where a version number is suffixed to the
binary name:
```
$ command -v ld.lld-11
/usr/bin/ld.lld-11
$ ls -l /usr/bin/ld.lld-11
lrwxrwxrwx 1 root root 25 May  2 08:32 /usr/bin/ld.lld-11 -> ../lib/llvm-11/bin/ld.lld
```
Before this patch, we would just use `/usr/bin/ld.lld-11` for
`-fuse-ld=` instead of resolving the symlink and using
`/usr/lib/llvm-11/bin/ld.lld` for `-fuse-ld=`.
However, this causes an issue where a user might be using their own
installation of LLVM and be using stock Debian/Ubuntu or apt.llvm.org
binaries at the same time (see the first entry in the before this
patch section below).
The versioned_binaries call is unnecessary because the script can handle
the apt.llvm.org …

build-llvm.py: Don't use versioned_binaries for ld.lld

---

build-llvm.py

Which is ultimately just the default value in cmake. We chose to change
it because we do a decent amount of configuration to it but there is
nothing fundamentally wrong with removing it.
Closes: #93

build-llvm.py: Clarify that '--clang-vendor' supports an empty string

---

build-llvm.py

This has been qualified with llvm-kernel-testing, which builds several
different configurations on four different kernel versions with
assertions enabled.
Normally, this would be done with the Linux 5.7 update but KCSAN, an
upcoming 5.8 feature, is requiring clang 11 or newer and some kernel
developers have expressed minor displeasure with that as they do not
want to deal with compiler issues. This option is meant specifically for
that use case and so we bump this to a revision that is new enough to
have the commits that KCSAN needs to work.
I am planning to do this on a monthly basis from now on, rather than
every Linux release.
Link: https://lore.kernel.org/lkml/20200520034426.GA1027673@ubuntu-s3-xlarge-x86/
Link: https://github.com/nathanchance/llvm-kernel-testing

build-llvm.py: Update known good revision

---

README.md

Neither the version of binutils or the list of architectures we build
for has been kept up to date. These two pieces of information are kept
up to date in other places, reference those so that this section does
not have to be updated anymore.

README: Two updates around binutils section

---

.github/workflows/lint.yml

What's Changed:
Added support for multiple paths, glob patterns, and single file caches 
**Increased performance and improved cache sizes using zstd for compression for Linux and macOS runners** 
Allowed caching for all events with a ref 
Created the @actions/cache npm package to allow other actions to utilize caching 
Added a best-effort step to delete the archive after extraction to reduces storage space 
Improved reliability of the download cache APIs 
Added retries to API calls that failed due to retryable errors 
Improved error handling during both cache upload and download
Increase cache size limit to 5 GB 
Add proxy support 
Improved reliability and speed of cache upload via chunked APIs
Increased per-cache size limit to 2 GB to match the per-repo limit
For further reference : …

workflows: upgrade action/cache to latest version

---

.github/workflows/lint.yml

- Bumps shellcheck-action to v2
- Pins yapf-action to the latest release as opposed to rolling (there were no changes to the workflow in the `v1.0..master` range, just documentation touchups)
- Switches cache to v2 so we can get incremental updates automatically

github: update workflow versions

---

kernel/build.sh

As suggested in #112, but I discarded the naming changes since I don't necessarily agree with them.

Fix header formatting for kernel buildscript

---

utils.py

Bump binutils to version 2.35.1 and use SHA512 checksum as upstream provides a sha512.sum file.
Run (here: x86-64):
$ python3 ./build-binutils.py -B ~/src/llvm-toolchain/build -I ~/src/llvm-toolchain/install -t x86_64-linux-gnu
Link: https://sourceware.org/pub/binutils/releases/sha512.sum
Link: https://sourceware.org/pipermail/binutils/2020-September/113375.html
Link: https://github.com/ClangBuiltLinux/tc-build/issues/118
Signed-off-by: Sedat Dilek <sedat.dilek@gmail.com>

utils.py: Bump binutils to v2.35.1 and use sha512sum (v4)

---

kernel/linux-5.8.3-allyesconfig.patch
kernel/linux-5.8.3-defconfig.patch

We are going with defining stpcpy as the solution rather than disabling
the builtin. Update the patch to reflect that so that it implicitly gets
proper testing from users.
Applied on top of `v5.8.3` with:
```
$ b4 am -o - -l https://lore.kernel.org/lkml/20200914161643.938408-1-ndesaulniers@google.com/ | git am -s
```

kernel: Update the stpcpy patch to the latest version upstream

---

build-llvm.py

Link: https://foundation.llvm.org/docs/branch-rename/

build-llvm.py: LLVM's primary branch is now named "main"

---

build-llvm.py

This is needed for CONFIG_DEBUG_INFO_BTF, which is becoming increasingly
more common. Add it to the list of targets that are enabled by default
so that it can be used without any issues.
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/129

build-llvm.py: Enable BPF backend by default

---

build-llvm.py

Give users the flexibility to define the values that they want so that
it is not necessary to continue to pollute the script with various
flags.
For example, if a user wants to limit the number of compile and link
jobs that ninja can do at one time:
```
$ ./build-llvm.py -D LLVM_PARALLEL_COMPILE_JOBS=2 LLVM_PARALLEL_LINK_JOBS=2
```
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/132

build-llvm.py: Add defines options

---

kernel/build.sh
kernel/linux-5.10.9.tar.xz.sha256
kernel/linux-5.10.tar.xz.sha256

We need the below commit to continue to do PGO without any issues.
https://git.kernel.org/stable/c/cb5a170e979e7d1b15185c9943c546bda2bc6445

kernel: Update to Linux 5.10.9

---

README.md

There are some presubmit checks that we do that make it a little hard
for some people to do drive by submissions without guidance. Add a small
section to clarify those and what is expected.
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/123

README: Add a contributing section

---

ci.sh

This will be the latest version of LLVM shortly so let's cut over now to
get ahead of testing early.

ci.sh: Use release/12.x for build testing

---

build-binutils.py

While adding support for m68k, I realized that our flags were similar enough for no reason. Clean them up, which makes adding new architectures easier.
This passes my build tests across all of the distributions I test.

Simplify the flags in build-binutils.py

---

build-binutils.py

This causes issues with arm64 natively on Debian, with both a Raspberry
Pi and Ampere eMAG server. This does not regress x86 based builds in my
testing.

build-binutils.py: Remove '--with-sysroot' configuration flag

---

build-llvm.py

Android's kernel/common tree has a patch that forces the use of
compiler-rt for the host tools so the build breaks when using a version
of LLVM built with this script because these are not available.
Link: https://android.googlesource.com/kernel/common/+/f14e5bfb39b776318133e00b8c066ce8a870e9ab

build-llvm.py: Build compiler-rt builtins

---

kernel/build.sh

We change all of the targets from "image_name modules" to "all" because
aspeed_g5_defconfig does not enable CONFIG_MODULES, resulting in an
error when targeting "modules". The "all" target builds the "modules"
target when CONFIG_MODULES is enabled.

kernel/build.sh: Build more ARCH=arm configs

---

build-llvm.py

Turns out I broke this in commit 6d2853a ("build-llvm.py: Add
'--full-toolchain'") because I never handled the case of '--projects'
being specified. Make the if statements a little simpler and handle
'--projects' again.

build-llvm.py: Fix handling of '--projects'

---

README.md

LLVM has certain minimum version requirements for cmake and the C
compiler (gcc/clang) and the build will error out if the host version
does not satisfy those requirements. This is expected and it is the
user's responsibility to make sure that their environment satisfies
those requirements according to LLVM's documentation.
Add a note that says the latest version of a distribution (in
particular, Debian and Ubuntu) should be used whenever possible so that
there are not unexpected build errors.
Remove the note about ld.lld for Debian and Ubuntu while we are here, it
is available as the "lld" package on Buster and Focal, which are the
latest versions of these distributions respectively.
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/163

README.md: Clarify that latest version of distribution should be used whenever possible

---

.github/CODEOWNERS

Right now, if someone opens a pull request that only touches non-Python
and non-shell files, no review is automatically requested, which could
result in things falling through the cracks.

.github/CODEOWNERS: Adjust file globs

---

clang-version.sh
kernel/build.sh

This pull request removes all assumptions that these scripts are being run on x86_64 hardware. It has been verified on both AArch64 and x86_64 hardware. See the individual commits for the improvements.

Improvements around non-x86_64 native use

---

build-llvm.py

Recently, I have been seeing thousands of warnings along the lines of:
```
LLVM Profile Warning: Unable to track new values: Running out of static counters.  Consider using option -mllvm -vp-counters-per-site=<n> to allocate more value profile counters at compile time.
LLVM Profile Warning: Unable to track new values: Running out of static counters.  Consider using option -mllvm -vp-counters-per-site=<n> to allocate more value profile counters at compile time.
LLVM Profile Warning: Unable to track new values: Running out of static counters.  Consider using option -mllvm -vp-counters-per-site=<n> to allocate more value profile counters at compile time.
```
I am not sure if this is due to a recent change in LLVM or because I do
not usually look at the output of `build-llvm.py` when running …

build-llvm.py: Dynamically link the instrumented stage against libLLVM

---

build-llvm.py
kernel/build.sh
utils.py

From bolt/README.md:
"BOLT is a post-link optimizer developed to speed up large applications.
It achieves the improvements by optimizing application's code layout
based on execution profile gathered by sampling profiler, such as Linux
perf tool."
Wire up support for BOLT into tc-build by generating a profile through
perf if it is support or BOLT's instrumentation if not. The profile is
generated by building a kernel with the final clang binary. The kernel
will either be the host architecture's defconfig if it is supported in
the lists of targets or the first target's defconfig.

tc-build: Initial BOLT support

---

build-llvm.py

LLVM commit 7d7771f34d14 ("[BOLT] Compact legacy profiles") makes the
merged profiles much smaller, which allows less powerful machines to do
BOLT. Add a note about it to the `--bolt` help text so that users are
aware that performing BOLT without that change will require much more
memory.
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/188
Link: https://github.com/llvm/llvm-project/commit/7d7771f34d14e0108adf02a6fd0b33943afae3da

build-llvm.py: Add a note about LLVM commit 7d7771f34d14 for BOLT

---

build-llvm.py

By default, the Linux target triples are based on glibc, which will not
work for musl-based distributions such as Alpine Linux.
Inherit the default target triple from the distribution's clang if it
exists so that everything works out of the box.

build-llvm.py: Add LLVM_DEFAULT_TARGET_TRIPLE when possible

---

ci.sh
kernel/build.sh

These are entirely mechanical changes, no functional changes are intended (famous last words...)
* Use lowercase for variables, as they are local to the script.
Uppercase is typically reserved for environment variables.
* Get rid of unnecessary braces. This is partially selfish, as I use
fish shell for my primary shell, which does not support braces around
variables at all, so this matches how I write variables on a daily
basis for consistency.
* Add a blank line between case statements to improve readability.
* Remove unnecessary '$?' or explicit exit code with '|| exit', as the
previous command's exit code will be passed along.

Improve shell script style

---

ci.sh
kernel/build.sh

These configurations work fine with 5.18.
NOTE: This is based on #195, just pay attention to the top commit.

kernel/build.sh: Support all*config for Hexagon, RISC-V, and s390

---

kernel/build.sh

The first patch fixes the length of the top and bottom headers in `kernel/build.sh`, as they are two equal signs too long.
The second patch adds a call to 'make kernelversion' to print the version of the kernel that is being built while performing PGO. This does not include any git information, as we could need to generate a configuration then throw it away before actually building.

kernel/build.sh: Print kernel version and small fix for header

---

utils.py

Qualified with:
```
$ ./build-binutils.py
```
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/201

utils.py: Update binutils to 2.39

---

build-llvm.py
utils.py

Otherwise, when running non-interactively (such as through GitHub
Actions), the output from these print statements might not appear before
the output of subprocess.run(), making it hard to decipher what has gone
wrong.

tc-build: Flush print commands to ensure output is properly ordered

---

build-llvm.py

The wrong folder is being used, which results in:
```
Traceback (most recent call last):
File ".../build-llvm.py", line 1620, in <module>
main()
File ".../build-llvm.py", line 1607, in main
linux_folder.as_posix())
AttributeError: 'NoneType' object has no attribute 'as_posix'
```

build-llvm.py: Fix 'LLVM source location does not exist' error message

---

build-binutils.py

The first patch is a small clean up that I noticed.
The second patch allows the user to specify a local binutils source, which is useful for testing master.
The third patch allows the user to skip installing binutils after building, which is useful for doing exclusively build testing, such as during a bisect of a build breakage.

Allow user to control binutils source folder location and installation

---

build-binutils.py
build-llvm.py
utils.py

The commit messages should be self explanatory but this PR updates tc-build to use f-strings (preferred in Python 3.6+) and eliminates as_posix() calls on path objects (possible after Python 3.6+), which cleans up the code a bit.

tc-build: Python updates

---

build-llvm.py

When a relative folder value is passed, it should be appended to the
current working directory, not tc-build's directory. Fix this by always
calling .resolve() as part of every folder's creation, which will
automatically expand relative paths as relative to the current working
directory, which behaves more in line with other utilities.

build-llvm.py: Fix using relative paths for folders

---

build-binutils.py
build-llvm.py
utils.py

The only reason that we built the gold plugin in the first place was to
support LTO on the Pixel 3, which used ld.gold instead of ld.lld, unlike
Android 4.14+ and mainline's LTO implementation.
The Pixel 3 has been EOL for several months now, so rip out all the gold
plugin enablement. With that, all the binutils functions in utils can be
moved into build-binutils.py directly, as build-llvm.py does not need to
know about binutils anymore.
Cc @kees, in lieu of #211.

tc-build: Stop building the gold plugin

---

build-llvm.py

CMake dominates the number of lines spewed during a build. Quiet the output when running with --quiet-cmake.
Signed-off-by: Kees Cook <keescook@chromium.org>

build-llvm.py: Add option to reduce CMake output

---

build-binutils.py

Same as commit 30a0244 ("build-llvm.py: Fix using relative paths for
folders") but for build-binutils.py. This should have been done then but
I rarely use build-binutils.py interactively, which is typically when
this fix would matter.

build-binutils.py: Fix using relative paths for folders

---

build-binutils.py
build-llvm.py
utils.py

Closes: https://github.com/ClangBuiltLinux/tc-build/issues/221

Print total script durations

---

build-llvm.py

When I set `LD` to any legit linker, for example `lld` or `gold`, it prints that it won't work but an incorrect one will go and fail during compilation.

build-llvm.py: Fix setting LD fails due to inverted test-check

---

build-llvm.py

Something is going wrong with the comprehension, as there is a
ValueError when unpacking the define (which makes little sense):
```
Traceback (most recent call last):
File ".../tc-build/./build-llvm.py", line 521, in <module>
defines = {k: v for define in args.defines for1 k, v in define.split('=', 1)}
File ".../tc-build/./build-llvm.py", line 521, in <dictcomp>
defines = {k: v for define in args.defines for k, v in define.split('=', 1)}
ValueError: too many values to unpack (expected 2)
```
This can be worked around by just using the `dict()` constructor, which is
simpler to read anyways.

build-llvm.py: Switch to dict() over dictionary comprehension

---

tc_build/binutils.py
tc_build/kernel.py
tc_build/llvm.py
tc_build/source.py
tc_build/tools.py

On OpenSUSE, there is a utils package in site-packages, which comes from
the pycparser package, conflicting directly with our own utils package.
To make sure everything works as expected, switch to absolute imports,
which avoids this pitfall. We already do this for the main Python
scripts.

tc_build: Switch to absolute imports

---

build-binutils.py
tc_build/binutils.py
tc_build/llvm.py

This pull request adds support for targeting LoongArch, as it may soon be possible to build the LoongArch Linux kernel with clang:
https://github.com/ClangBuiltLinux/linux/issues/1787
The first two patches just clean up a couple things I noticed while writing this series.
The third patch adds support for validating the targets that the user passes; this is largely tangential to this series but `get_all_targets()` is needed for checking if LoongArch can be enabled in LLVM and it is a logical extension to validate the user's input as well.
Finally, the last three patches wire up LoongArch into `build-binutils.py`, `build-llvm.py`, and `kernel/build.sh` (as a no-op for now).
If there are any questions or comments, please let me know.

Add support for LoongArch

---

ruff.toml

Reading the bandit documentation, these warnings are low severity and it
would make the code significantly worse to try and work around them, so
opt out of them. These calls are working as intended and this project is
designed to be used interactively so injection is not a concern.
Link: https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html
Link: https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

ruff.toml: Disable S603 and S607

---

tc_build/kernel.py

A future kernel change will make pseries_defconfig a little endian
configuration. To keep PGO coverage for big endian, switch to
ppc64_guest_defconfig, which is roughtly equivalent.
Link: https://lore.kernel.org/20230414132415.821564-32-mpe@ellerman.id.au/

tc_build: kernel: Adjust PowerPC64 configuration target

---

build-llvm.py

This has been qualified on aarch64 and x86_64 hosts using my [llvm-kernel-testing](https://github.com/nathanchance/llvm-kernel-testing) repository.
I had initially wanted to use https://github.com/llvm/llvm-project/commit/99a1aeefb3d6be2018b591ed8c184c6f75fac386 as the known good revision for this upgrade (which is the parent of https://github.com/llvm/llvm-project/commit/d81ce04587c006b6731198956c522c93d0df105, which broke certain builds and is still being dealt with on the Linux side) but that revision is susceptible to warnings caused by https://github.com/llvm/llvm-project/commit/0123deb3a6f0a83095287f51b07c77b7b43ab847, which was fixed by https://github.com/llvm/llvm-project/commit/844e9534c6d99ddb6bada740839760fa24d17cb6, which occurs after …

Update default PGO kernel to 6.4.0 and update known good revision

---

tc_build/llvm.py

A new ruff warning suggests switching to `Path.glob()` over `glob.glob()`:
```
tc_build/llvm.py:258:12: PTH207 Replace `glob` with `Path.glob` or `Path.rglob`
```
While it is a little more verbose, it allows us to drop an import, so
just do it to silence the warning.

tc_build: llvm: Switch to Path.glob()

---

build-llvm.py
tc_build/kernel.py

This pull request updates the default PGO kernel to 6.5.0 and bumps the known good revision for building the kernel.
As part of the update to 6.5.0, we are able to build `ARCH=powerpc allmodconfig` without any configuration changes and update the build options for `ppc64_guest_defconfig`. With this, we require users who supply their own kernel source to be on at least 6.5.0 as well.

Update default PGO kernel to 6.5.0 and update known good revision

---

build-llvm.py
tc_build/llvm.py

`build/llvm/bootstrap/bin/` contains a lot of LLVM and Clang tools that are not needed to build the kernel or later stages of Clang. Utilize LLVM_DISTRIBUTION_COMPONENTS to build fewer targets for 'bootstrap' and 'instrumented'. The `final` directory still contains everything.
When BOLT is disabled, we now just build the following executables:
```
% ls build/llvm/bootstrap/bin/
clang@     clang-cpp@     llvm-ar*          llvm-objcopy*   llvm-readelf@  wasm-ld@
clang++@   clang-tblgen*  llvm-lit*         llvm-objdump*   llvm-readobj*  ld64.lld@
clang-18*  lld*           llvm-min-tblgen*  llvm-profdata*  llvm-strip@    ld.lld@
clang-cl@  lld-link@      llvm-nm*          llvm-ranlib@    llvm-tblgen*
```
Tested:
./build-llvm.py --install-folder $PWD/install --projects clang lld …

build-llvm.py: Utilize LLVM_DISTRIBUTION_COMPONENTS to build fewer targets

---

tc_build/llvm.py

Copying .o files into archives are wasteful. Utilize thin archives to reclaim wasted space. Use the deprecated -T for compatibility with binutils<2.38 and llvm-ar<14.
See https://maskray.me/blog/2022-01-16-archives-and-start-lib for some notes about thin archives and useless archive symbol tables. In an ideal world where GNU ld did not read archive symbol tables, we could specify -S to save more space.

build-llvm.py: Utilize thin archives

---

tc_build/llvm.py

See the individual commits for the finer details.

Adjust distribution components style and fix building with PGO

---

tc_build/llvm.py

It is possible to use `--projects` to build certain combinations of subprojects, such as just `llvm` or `clang` to build just LLVM or LLVM and clang respectively. When either the `clang` or `lld` subproject is not enabled, there is an error when running `cmake` due to their targets being present in the distributions components list.
Only add them to `distribution_components` if the projects that contain them are enabled.

tc_build: llvm: Fix distribution_components with disabled projects

---

build-llvm.py
tc_build/llvm.py

It can be useful to select subtargets, like `clang` or `llvm-ar`, to build single tools when issues are isolated to them, which can reduce build time. This provides tangible benefits when bisecting, as an issue can be isolated down to a single commit in less time.
As part of this implementation, the build target parameter is added as a member to `LLVMBuilder` and changed to a list to be more flexible and fit in more with how customizing the builder works in the rest of `tc_build/`.

build-llvm.py: Add '--build-targets'

---

build-llvm.py

This has been qualified on aarch64 and x86_64 hosts using my llvm-kernel-testing repository.
LoongArch builds are currently broken at this revision but [the fix](https://lore.kernel.org/20231102-loongarch-always-inline-percpu-ops-v2-1-31c51959a5c0@kernel.org/) should hopefully be picked up and backported to all relevant releases in a relatively timely manner, so I don't think it is worth changing the revision just for this.

Update default PGO kernel to 6.6.0 and update known good revision

---

ci.sh

The first change moves `ci.sh` to use `release/17.x`, the latest stable release branch.
The second makes the build slimmer so that there is less room for random build breakage as well as faster builds. This is just a smoke test after all.

A couple of ci.sh updates

---

tc_build/llvm.py

Otherwise, they will get added to each invocation of `ninja`. `build_target` should have been added to just the `self.run_cmd(ninja_cmd)`. While this does not (currently) cause any problems, it is unnecessary to specify the base build targets on each subsequent invocation of `ninja` because they will have already been built.
To make it clearer for the future, rename `ninja_cmd` to `base_ninja_cmd`.

tc_build: llvm: Move use of build_targets out of ninja_cmd

---

tc_build/llvm.py

Resolves the following warnings when performing BOLT:
BOLT-WARNING: '-reorder-blocks=cache+' is deprecated, please use '-reorder-blocks=ext-tsp' instead
BOLT-WARNING: specifying non-boolean value "3" for option -split-functions is deprecated
Which matches the updated docs:
https://github.com/llvm/llvm-project/commit/38fb7d56e543f3cd137a79d6e6331b697ef9f92c
https://github.com/llvm/llvm-project/commit/96f6ec5090c2f7a1e4804693cbb84c29c574b3de

tc_build: llvm: Update BOLT flags

---

build-llvm.py

Without `--full-toolchain`, we do not build `clang-tblgen` and `llvm-tblgen` as part of the distribution in the instrumented build. As a result, building LLVM as PGO training data errors out. Fix this by using the bootstrap versions, which should be available and sufficient.

build-llvm.py: Fix PGO using LLVM as training data without '--full-toolchain'

---

build-llvm.py

This has been qualified on aarch64 and x86_64 hosts using my [llvm-kernel-testing](https://github.com/nathanchance/llvm-kernel-testing) repository.
There is one small regression (https://github.com/ClangBuiltLinux/linux/issues/1966) but I do not think it is worth delaying the known good revision update over. Once that has been fixed, I will bump the known good revision to that revision.

Update default PGO kernel to 6.7.0 and update known good revision

---

build-binutils.py

This is the latest binutils release:
https://lists.gnu.org/archive/html/info-gnu/2024-01/msg00016.html

build-binutils.py: 2.42

---

ruff.toml

There is a deprecation warning for top level lint settings:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `ruff.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
```
Move these under the lint section. Additionally, update the link to the rules.

ruff.toml: Update for 0.2.0

---

tc_build/tools.py

It was moved in https://github.com/llvm/llvm-project/commit/81e20472a0c5a4a8edc5ec38dc345d580681af81.
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/262

tc_build: tools: Update location of LLVM_VERSION_MAJOR

---

src/20240319_nathan_hexagon_vmlinux_lds_s_handle_attributes_section.patch
src/35f20786c481d5ced9283ff42de5c69b65e5ed13.patch
src/75b5ab134bb5f657ef7979a59106dce0657e8d87.patch

See the individual patch commit messages to see what is being fixed.

Add patches to fix performing PGO with current LLVM main

---

build-llvm.py

This has been qualified on aarch64 and x86_64 hosts using my [llvm-kernel-testing](https://github.com/nathanchance/llvm-kernel-testing) repository.

Update default PGO kernel to 6.8.0 and update known good revision

---

build-llvm.py
tc_build/kernel.py

See the individual changes for the full details. This has been qualified on aarch64 and x86_64 hosts using my [llvm-kernel-testing](https://github.com/nathanchance/llvm-kernel-testing) repository.

Update default PGO kernel to 6.9.0 and update known good revision

---

tc_build/llvm.py

`LLVM_ENABLE_TERMINFO` has been removed in tip of tree LLVM, so we need to stop adding it unconditionally to avoid a warning from CMake during configuration.
```
CMake Warning:
Manually-specified variables were not used by the project:
LLVM_ENABLE_TERMINFO
```
Link: https://github.com/llvm/llvm-project/commit/6bf450c7a60fa62c642e39836566da94bb9bbc91

tc_build: llvm: Handle removal of LLVM_ENABLE_TERMINFO

---

build-llvm.py
src/2bac084468847cfe5bbc7166082b2a208514bb1c.patch
tc_build/kernel.py

I have not included an update to the known good revision this time around, as there are several known regressions in tip of tree and I have not had time to try and qualify both that uprev and this one. This one should be safe with the coverage that we have had in CI.

Update DEFAULT_KERNEL_FOR_PGO to 6.10.0

---

tc_build/kernel.py
tc_build/source.py

Include more information when setting up the source, such as:
- An informational print about downloading the source in case the connection is slow so the user knows something is happening in the background.
- An informational print for every patch that gets applied, so that the user is aware the source is not clean.
- Updating the wording of a message to be a little more descriptive about source location.
- Cleaning up the spelling in one message.

tc_build: Improve source set up logging

---

tc_build/kernel.py

This is the same warning that we already disable for `pylint`, for the reasons outlined in the comment block above this.
```
tc_build/kernel.py:82:33: SIM115 Use a context manager for opening files
|
80 |             # always cleaned up.
81 |             # pylint: disable-next=consider-using-with
82 |             kconfig_allconfig = NamedTemporaryFile(dir=self.folders.build)
|                                 ^^^^^^^^^^^^^^^^^^ SIM115
83 |
84 |             configs_to_disable = ['DRM_WERROR', 'WERROR']
|
Found 1 error.
```

tc_build: kernel: Silence new ruff warning (SIM115)

---

tc_build/llvm.py

There is some effort to build `ARCH=sparc` with Clang. Add it to the default targets list so that toolchains built with tc-build can easily test these patches.

tc_build: llvm: Add Sparc to default targets

---

build-llvm.py
tc_build/binutils.py

See the individual changes for the full details. This has been qualified on aarch64 and x86_64 hosts using my [llvm-kernel-testing](https://github.com/nathanchance/llvm-kernel-testing) repository.

Update DEFAULT_KERNEL_FOR_PGO to 6.13.0 and bump known good revision

---

tc_build/binutils.py

We disable installation of docs for LLVM already, similarly modify the Binutils build process to redirect the installation of doc files to a temporary directory (/tmp/tc-build/deleteme) and delete it after the build and installation process finishes.
Files that get redirected:
$ find /tmp/tc-build/deleteme/
<details>
<summary>Click to expand</summary>
> /tmp/tc-build/deleteme/dir
> /tmp/tc-build/deleteme/ldint.info
> /tmp/tc-build/deleteme/ld.info
> /tmp/tc-build/deleteme/binutils.info
> /tmp/tc-build/deleteme/ctf-spec.info
> /tmp/tc-build/deleteme/bfd.info
> /tmp/tc-build/deleteme/as.info
> /tmp/tc-build/deleteme/gprof.info
> /tmp/tc-build/deleteme/sframe-spec.info
> /tmp/tc-build/deleteme/gprofng.info
> /tmp/tc-build/deleteme/man1/loongarch64-linux-gnu-ld.1
> …

tc_build/binutils: Dont install unwanted man pages and info files

---

ci.sh

While the branch has not been released yet, we want to make sure that we start testing early to catch any potential problems.

ci.sh: Update to release/20.x

---

tc_build/llvm.py

Per the new deprecation warning: https://github.com/llvm/llvm-project/commit/b593110d89aea76b8b10152b24ece154bff3e4b5
Do the check based on `LLVM_VERSION_MAJOR` from source to avoid a complicated and potentially hard to maintain dynamic check.

tc_build: llvm: Move compiler-rt to LLVM_ENABLE_RUNTIMES

---

tc_build/llvm.py

In order for the compiler-rt profile library to be built after the switch to the runtimes build, the runtimes target needs to be added to the distribution components. This fixes the build with PGO.

tc_build: llvm: Add 'runtimes' to distribution

---

tc_build/llvm.py

The deprecation warning was merged a little before the LLVM 20 branch, so use the runtimes build for LLVM 20 and newer

tc_build: llvm: Use runtimes build for LLVM 20 and newer

---

.github/workflows/lint.yml
ruff.toml

According to https://endoflife.date/python Python 3.8 no longer has security support as of 5 months ago.
IMO we should also drop Python 3.9 since it will lose security support 7 months from now but we can defer that
to when the time arrives, hence it is not included in this PR.

fix(ci): drop EOL Python version

---

ci.sh

Should fix failing ci builds like [14091483405 ](https://github.com/ClangBuiltLinux/tc-build/actions/runs/14091483405) and [14091491225](https://github.com/ClangBuiltLinux/tc-build/actions/runs/14091491225).

ci.sh: Update mirrorlist before installing dependencies

---

tc_build/llvm.py

This turns off linking against libxml2 by default and makes sure that we do not dynamically link against the LLVM libraries. See the commit messages for the individual details.

Adjust the base LLVM configuration

---

tc_build/llvm.py
tc_build/utils.py

When performing BOLT on Apple Silicon (such as when building in a UTM virtual machine), running clang hangs due to instrumentation between exclusive load and store instructions (see the LLVM issue linked in the comments for more information).
Detect when running on Apple Silicon and enable the conservative instrumentation option to avoid hitting this issue.

tc_build: Enable '--conservative-instrumentation' for BOLT on Apple Silicon

---

tc_build/kernel.py

arm64 defconfig is quite large relative to other defconfigs, which makes it take longer to build than most other architectures and makes profiling data consume much more space.
virtconfig was introduced in 6.3 to turn off a lot of code that will not run under a virtual machine, slimming up the build configuration and making it faster. Measuring on two different machines, virtconfig is 50% faster to build than defconfig.
Benchmark 1: virtconfig
Time (mean ± σ):     120.938 s ±  0.707 s    [User: 6864.867 s, System: 910.128 s]
Range (min … max):   120.413 s … 121.742 s    3 runs
Benchmark 2: defconfig
Time (mean ± σ):     180.490 s ±  0.271 s    [User: 10490.721 s, System: 1470.871 s]
Range (min … max):   180.210 s … 180.751 s    3 runs
Summary
virtconfig ran
1.49 ± 0.01 times faster than …

tc_build: kernel: Use virtconfig for arm64 profiling target

---

build-llvm.py

This has been lightly qualified on an aarch64 and x86_64 host with the environment and configuration that I build the kernel.org toolchains with.

Update PGO kernel to 6.17 and bump known good revision
