ClangBuiltLinux/tc-build

build-llvm.py
Pretty self explanatory commit messages :)
=> Some small fixups

build-binutils.py
Removes a little duplication and makes everything look cleaner in terms
of formatting.
=> build-binutils.py: Consolidate make command

README.md, build-binutils.py, build-llvm.py
This just makes more sense in my opinion.
=> tc-build: Change default install folder to "install"

build-binutils.py
This is the result of:
```
$ sed -i 's/root/root_folder/g' build-binutils.py && yapf build-binutils.py
```
I would prefer that #7 and #8 are merged ahead of this because I can run that one liner upon rebase super easily. I've just pushed it now as a heads up that I want this done.
=> build-binutils.py: Rename root to root_folder for consistency

build-llvm.py
This causes issues with older versions of LLVM on some people's
hardware. Make it opt in it won't mess with people who just run
'./build-llvm.py' and people who want it can still enable it.
At the same time, drop the -O2 flag; release LLVM builds are compiled
with -O3 and it overrides our choice anyways (always appears after
CMAKE_C_FLAGS).
=> build-llvm.py: Only apply native optimizations if specifically requested

.github/CODEOWNERS
=> CODEOWNERS: Update to my new username

README.md, build-llvm.py
See the commit messages for more information :)
=> Documentation updates

build-binutils.py, build-llvm.py
* Allow any `-march`/`-mtune` value from @kdrag0n
* Rename `--no-pull` to `--no-update`, which I think looks better
* Add `--no-ccache` flag for easy clean build testing
* Allow full LTO in addition to ThinLTO by converting `--thin-lto` into `--lto=`
=> Parameter updates

build-llvm.py
See all of the commit messages for the reasoning. This addresses #42.
=> Testing improvements

build-binutils.py, build-llvm.py
Now that we have triaged/dealt with the outstanding issues:
https://github.com/ClangBuiltLinux/linux/issues/571
https://github.com/ClangBuiltLinux/linux/issues/610
=> tc-build: Add support for MIPS

build-binutils.py
Mirrors https://github.com/ClangBuiltLinux/continuous-integration/pull/196.
=> build-binutils.py: Add powerpc64-linux-gnu

build-llvm.py
Each commit message should be fairly self explanatory :)
=> Fix '--use-good-revision' while improving compatibility with older versions of git

.github/workflows/main.yml, build-llvm.py, clang-version.sh, kernel/build.sh
[Shellcheck ](https://github.com/koalaman/shellcheck)+ [YAPF ](https://github.com/google/yapf) to ensure consistency and quality.
=> tc-build: Add two GitHub Actions

build-llvm.py
=> build-llvm: clone over https instead of clear text

build-llvm.py, kernel/build.sh
See each individual commit for reasoning.
=> Display toolchain version information to the user

ci.sh
I came across these when using it locally before pushing #90. Each should be fairly uncontroversial.
=> Some ci.sh fixes

utils.py
=> utils: Upgrade to binutils-2.35

kernel/build.sh
All the commit messages should break everything down fairly well.
=> Kernel build script updates

build-llvm.py
The commit messages should be self explanatory.
=> build-llvm.py: Some improvements around '--build-stage1-only' and optimization options

build-llvm.py
Each commit should be fairly self explanation.
=> Some small documentation fixes

kernel/build.sh
Second commit is the meat, the commit message should have the full details.
=> Some fixes for kernel/build.sh with LLVM=1

README.md, build-binutils.py, build-llvm.py, kernel/build.sh
Clear Linux is rather odd in a few places (see the individual commit messages for the full details). I feel this distribution is starting to grow so I think it is worth supporting here.
cc @kdrag0n, just in case there is anything here that might break Proton Clang.
This has been run through my `podman` testing infrastructure ([link to current version](https://github.com/nathanchance/scripts/blob/991930822f98e153ebbfad6a12c7c170e2439a49/env/stubs/cbl#L112-L312)), where it passes for all distributions still.
=> Support for Clear Linux

build-llvm.py
Qualified with https://github.com/nathanchance/llvm-kernel-testing:
<details><summary>5.12.5</summary>
<p>
```
arm32 multi_v5_defconfig successful in 0:00:58
arm32 multi_v5_defconfig qemu boot successful
arm32 aspeed_g5_defconfig successful in 0:00:52
arm32 aspeed_g5_defconfig qemu boot successful
arm32 multi_v7_defconfig successful in 0:02:13
arm32 multi_v7_defconfig qemu boot successful
arm32 allmodconfig successful in 0:11:05
arm32 allnoconfig successful in 0:00:13
arm32 tinyconfig successful in 0:00:13
arm32 allyesconfig successful in 0:10:47
armv7 alpine config successful in 0:03:04
armv7 alpine config qemu boot successful
armv5 archlinux config successful in 0:02:32
armv7 archlinux config successful in 0:05:32
armv7 archlinux config qemu boot successful
arm32 debian config …
```
=> build-llvm.py: Update known good revision

README.md
This was brought up by @bensuperpc in #159 and I discovered a couple of extra packages that were needed in certain configurations as well.
=> Update list of Arch Linux packages

kernel/build.sh
If a user runs `build-llvm.py` with `--pgo kernel-{def,allmod}config`, the
script will wait for their input because a patch has already been
applied:
```
patching file arch/powerpc/include/asm/barrier.h
Reversed (or previously applied) patch detected!  Assume -R? [n]
```
The script should be totally non-interactive. Unfortunately, GNU patch
returns 1 when `patch -N` detects a previously applied patch so we need
to wrap its output and parse it for this phrase, which is not fatal in
our context. Every other message is treated as fatal and printed in
full.
`git apply` is another option but it does not appear to work when patching
untracked files, even with `--no-index` and `--unsafe-paths`.
Fixes: 67f40f7 ("kernel/build.sh: Update patching logic")
=> kernel/build.sh: Fix patch application with two PGO kernel runs

README.md
Remove gcc and g++ (Replaced by build-essential)
Change python3 to python3-dev (Install python3-distutils package), fix issues with PGO and check-targets:
`python3 build-llvm.py --assertions --show-build-commands --shallow-clone --branch "release/12.x" --shallow-clone --projects "all" --targets X86 --lto=thin --build-type=Release --check-targets clang llvm --pgo llvm`
I have these issues if i don't install python3-distutils:
```
[380/660] Linking CXX executable tools/clang/unittests/Tooling/ToolingTests
[380/660] Running the Clang regression tests
llvm-lit: /tc-build/llvm-project/llvm/utils/lit/lit/llvm/config.py:385: note: using clang: /tc-build/build/llvm/stage2/bin/clang
-- Testing: 27077 tests, 12 workers --
Testing:  0.. 10.. 20.. 30.. 40..
FAIL: Clang :: …
```
=> Update debian packages

kernel/build.sh
Commit messages should be fairly self explanatory :)
=> A couple of small fixes

.github/workflows/build.yml
Link: https://github.com/actions/checkout/releases/tag/v3.0.0
=> workflows: Bump actions/checkout to v3

ci.sh
This is the latest stable branch.
=> ci.sh: Use release/14.x for testing

build-llvm.py
In commit b8ef75c ("tc-build: Initial BOLT support"), I added a warning
about a potential issue with BOLT + PGO, which has now been fixed in
LLVM properly. Dynamically check the LLVM source for this fix and avoid
warning the user when they have it.
Link: https://github.com/llvm/llvm-project/issues/55004
=> build-llvm.py: Adjust BOLT + PGO warning for upstream fix

build-llvm.py
This modernizes build-llvm.py a little bit more.
=> tc-build: Eliminate os.path usage and more f-strings

.github/workflows/lint.yml, build-binutils.py, build-llvm.py, utils.py
See the individual commits for the warnings and fixes.
Depends on https://github.com/ClangBuiltLinux/actions-workflows/pull/4.
=> tc-build: Python linting fixes

build-binutils.py, utils.py
Just a few small changes that I thought about during recent pull requests; they should be pretty self explanatory.
=> Two small miscellaneous improvements

build-binutils.py
Signed-off-by: Ahmad Thoriq Najahi <najahi@zephyrus.id>
=> utils.py: Update to binutils 2.40

build-binutils.py
https://sourceware.org/pipermail/binutils/2023-July/128719.html
=> build-binutils.py: 2.41

.github/workflows/build.yml
This is the latest major version of the checkout action.
=> workflows: Update to actions/checkout@v4

build-binutils.py
These values are not valid `-mtune` values, so the build errors.
Do not add `-mtune` at all, unless one of these values has been specified, in which case `-mtune=native` is a safe choice.
Closes: https://github.com/ClangBuiltLinux/tc-build/issues/255
Link: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
=> build-binutils.py: Fix error with x86-64-v{2,3,4} as value to '-m'

ci.sh
This is the latest stable release branch.
=> ci.sh: Update to release/19.x

tc_build/llvm.py
The CLANG_ENABLE_ARCMT option was deprecated in [commit](https://github.com/llvm/llvm-project/commit/c4a019747c98ad9326a675d3cb5a70311ba170a2) due to the removal of ARCMigrate. So check if the option exists before disabling it to avoid cmake warnings.
=> tc-build: Handle the deprecation of CLANG_ENABLE_ARCMT

build-llvm.py
I am going to be unable to do my full qualification for updating these in about a month's time, so they will not be as well tested but I am still going to be avoiding major known issues still.
=> Update PGO kernel to 6.14 and bump known good revision

tc_build/kernel.py
See the individual changes for the full details of each one.
=> Various fixes for PGO with older LLVM versions

build-binutils.py
Link: https://inbox.sourceware.org/binutils/87bjp69d0q.fsf@redhat.com/
=> build-binutils.py: 2.45
